[package]
name = "oxhttp"
version = "0.1.2"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["HTTP"]
repository = "https://github.com/oxigraph/oxhttp"
description = """
Very simple implementation of HTTP 1.1 (both client and server)
"""
edition = "2018"

[dependencies]
httparse = "1"
native-tls = { version = "0.2", optional = true }
url = "2"